<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>IntuneODCCollector</AssemblyName>
    <RootNamespace>IntuneODCCollector</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0.0</FileVersion>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
  </PropertyGroup>
</Project>
